name: IT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_DBNAME: itest_kvstore_pgx

jobs:

  postgres14test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout   5s
          --health-retries   5
          
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      env:
        ITEST_KVSTORE_PGX_DBNAME: ${{ env.TEST_DBNAME }}
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
